syntax = "proto3";

package proto;

message SensorExtrinsic {
  double time_offset = 1;
  double tx = 2;
  double ty = 3;
  double tz = 4;
  double rx = 5;
  double ry = 6;
  double rz = 7;
  double rw = 8;
}

message CameraParam {
  // Camera-to-IMU/body transform: p_imu = extrinsic * p_camera.
  SensorExtrinsic extrinsic = 1;
  double fx = 2;
  double fy = 3;
  double cx = 4;
  double cy = 5;
  double k1 = 6;
  double k2 = 7;
  double k3 = 8;
  double k4 = 9;
  string name = 11;
}

message Matrix3 {
  repeated double data = 1; // 存储3x3矩阵的9个元素
}

message Vector3 {
  repeated double data = 1; // 存储3个元素的向量
}

message ImuIntrinsicTpmIcra2014 {
  Matrix3 Ta = 1;
  Matrix3 Ka = 2;
  Vector3 Ba = 3;

  Matrix3 Tg = 4;
  Matrix3 Kg = 5;
  Vector3 Bg = 6;
}

message ImuIntrinsic {
  oneof imu_model { ImuIntrinsicTpmIcra2014 tpm = 1; }
}

message LidarIntrinsicSimple {
  double e = 1;
  repeated double s = 2;
}

message LidarIntrinsic {
  oneof lidar_model { LidarIntrinsicSimple simple = 1; }
}

message SensorCalib {
  bool has_encoder = 1;
  SensorExtrinsic lidar_to_encoder = 2;
  SensorExtrinsic encoder_to_imu = 3;
  LidarIntrinsic lidar_intrinsic = 4;
  ImuIntrinsic imu_intrinsic = 5;
  repeated CameraParam camera_param = 6;
}
