# Stage 1: Builder
FROM registry.cn-hangzhou.aliyuncs.com/c137/reality-capture-toolkit:base-cuda AS builder


# install packages
RUN apt-get update \
    && apt-get install -q -y libtool python3-jinja2 flex bison libxtst-dev autoconf automake autoconf-archive \
       unzip zip '^libxcb.*-dev' libx11-xcb-dev libgl1-mesa-dev libxrender-dev libxi-dev  libxkbcommon-dev libxkbcommon-x11-dev gfortran \
       libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxxf86vm-dev \
       pkg-config python3.12-venv libxcursor-dev libxdamage-dev libxinerama-dev \
    && rm -rf /var/lib/apt/lists/*


# 1. chekcout vcpkg version
# 2. edit vcpkg options, By default, COLMAP uses nvcc -arch=native for CUDA compilation. If the build environment lacks a GPU, it defaults to compute_52, which may limit compatibility. Changing it to nvcc -arch=all ensures broader support across NVIDIA GPUs.
# 3. build vcpkg binary
RUN mkdir /buildspace && cd /buildspace \
    && git clone https://github.com/microsoft/vcpkg \
    && cd /buildspace/vcpkg \
    && git checkout e9d0d6fe71ec440a6a7906f92f941a181b937556 \
    && sed -i '/--disable-test-modules/a \        "--disable-ipv6"' /buildspace/vcpkg/ports/python3/portfile.cmake \
    && sed -i 's/set(VCPKG_LIBRARY_LINKAGE static)/set(VCPKG_LIBRARY_LINKAGE dynamic)/' /buildspace/vcpkg/triplets/x64-linux.cmake \
    && sed -i '/set(VCPKG_CMAKE_SYSTEM_NAME Linux)/a set(VCPKG_BUILD_TYPE release)' /buildspace/vcpkg/triplets/x64-linux.cmake \
    && sed -i 's/set(CUDA_ARCHITECTURES "native")/set(CUDA_ARCHITECTURES "all")/' /buildspace/vcpkg/ports/colmap/portfile.cmake \
    && cd /buildspace/vcpkg \
    && ./bootstrap-vcpkg.sh

RUN for i in $(seq 1 20); do \
      /buildspace/vcpkg/vcpkg install boost pcl colmap[cuda] opencv cgal pdal rapidjson gtest mimalloc[override] crashpad yaml-cpp --recurse && break || sleep 10; \
    done \
    && rm -rf /buildspace/vcpkg/downloads /buildspace/vcpkg/buildtrees /buildspace/vcpkg/packages /var/lib/apt/lists/* /root/.cache/vcpkg



# Stage 2: Final Runtime Image
FROM registry.cn-hangzhou.aliyuncs.com/c137/reality-capture-toolkit:base-cuda

COPY --from=builder /buildspace/vcpkg /buildspace/vcpkg

CMD ["bash"]
