# Stage 1: Build Dependencies
FROM registry.cn-hangzhou.aliyuncs.com/c137/reality-capture-toolkit:base-cuda AS base

# install packages for vcpkg
RUN apt-get update \
    && apt-get install -q -y libtool python3-jinja2 flex bison libxtst-dev autoconf automake autoconf-archive \
       unzip zip '^libxcb.*-dev' libx11-xcb-dev libgl1-mesa-dev libxrender-dev libxi-dev  libxkbcommon-dev libxkbcommon-x11-dev gfortran \
       libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxxf86vm-dev \
       pkg-config python3.12-venv libxcursor-dev libxdamage-dev libxinerama-dev \
       clang \
    && rm -rf /var/lib/apt/lists/*

# install cudss
RUN apt-get update \
    && apt-get install -q -y cudss \
    && rm -rf /var/lib/apt/lists/*


# Stage 2: Builder
FROM base AS builder

RUN mkdir /buildspace && cd /buildspace \
    && git clone -b develop https://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@github.com/kekeliu-whu/vcpkg.git \
    && cd /buildspace/vcpkg \
    && ./bootstrap-vcpkg.sh

RUN for i in $(seq 1 20); do \
    /buildspace/vcpkg/vcpkg install boost pcl colmap[cuda] ceres[cuda] opencv cgal pdal rapidjson gtest mimalloc[override] crashpad yaml-cpp tinyxml --recurse && break || { \
      echo "Attempt $i failed. Retrying in 10 seconds..."; sleep 10; }; \
  done; \
  if [ $i -eq 20 ]; then echo "Installation failed after 20 attempts." && exit 1; fi; \
  rm -rf /buildspace/vcpkg/downloads /buildspace/vcpkg/buildtrees /buildspace/vcpkg/packages /var/lib/apt/lists/* /root/.cache/vcpkg


# Stage 3: Final Runtime Image
FROM base

COPY --from=builder /buildspace/vcpkg /buildspace/vcpkg

CMD ["bash"]
