ros:
  imu_topic: /imu
  encoder_topic: /lidar_to_platform
  lidar_topic: /hesai/pandar
  gnss_topic: /gnss_data
  offline_mode_start_frame_id: 0
  offline_mode_end_frame_id: 1000000
  offline_mode_speed_ratio: 5               # multiply the publish rate by FACTOR

preprocess:
  range_min: 0.3
  range_max: 300
  body_mask_min: [ -0.5, -0.4, -1.5 ]
  body_mask_max: [ 0.5, 0.8, 0.5 ]
  sweep_duration: 0.1
  sweep_cut_auto: true

downsample:
  area_method: 0             # L2 use method 0, cube_4_side method
  init_pca_downsample_dis: 1.5
  base_downsample_dis: 0.2
  max_downsample_dis: 1.5
  ref_downsample_point_num: 4000

init_param:
  init_pos_std: 0.001
  init_vel_std: 0.001
  init_rot_std: 0.001
  init_acc_bias_std: 0.001
  init_gyro_bias_std: 0.0003

kf:
  acc_std: 0.014
  gyr_std: 0.0017
  acc_bias_std: 0.0004
  gyr_bias_std: 0.0001
  max_iter: 5
  acc_keep_std_limit: 0.5
  gyro_keep_std_limit: 0.5
  use_gnss: false
  use_vio: false
  use_edge: false
  k_for_adaptive_search: 0.003


# temp
knn_min_points: 6
knn_max_points: 6
knn_distance_limit: 0.4

resolution: 0.1   # 0.2m
small_scale: 60   # 30 * 0.2 --> 6m
large_scale: 10   # 6 * 10   --> 60m
map_scale: 5      # 60 * 5  --> 300m的正方体，要求必须是奇数
forget_range: 200             # Local map forget radis, important parameter and don't modify
forget_ts: 200                # Local map forget time, important parameter and don't modify

enable_normal_filter: true    # 法向过滤
enable_forget_point: false    # 逐点遗忘， 暂时无用
enable_forget: true           # 开启遗忘
enable_dynamic: false         # 开启动态加载，与地图遗忘是互斥功能
enable_dynamic_backend: false # 允许动态加载单独开线程并行
replace_points_flag: 0        # 0: 保留旧点， 1：保留新店，2：新旧融合

pcd_path: '/home/youyuan/lio_pcd/'
pcd_path_onboard: '/home/youyuan/lio_pcd/'
test_data_path: '/home/youyuan/文档/K1.las'
